nginx:
  build: nginx
  ports:
    - 80:80
    - 443:443
  links:
    - web:web

web:
  build: .
  volumes:
    - /usr/src/app/venv
    - /usr/src/app/node_modules
    - /usr/src/app/bower_components
    - /usr/src/app/static
  environment:
    ENV: PROD
  env_file: prod.env
  command: gunicorn -b 0.0.0.0:8000 --access-logfile - --error-logfile - pythonph.wsgi
